# docker-compose file setting up local testing environment for AWS services alongside serverless plugins
# Feel free to comment out unnused services

version: '3.8'
services:
    
    serverless-container:                                             # Setting up Serverless development environment        
        image: esteveslima/serverless-template-image:latest           
        build:
            context: .
            dockerfile: Dockerfile
        volumes:
            - ./:/serverless-template                                  
            - ./resources/config/aws/.aws:/home/node/.aws             
        working_dir: /serverless-template      
        environment:
            - NODE_TLS_REJECT_UNAUTHORIZED=0                          
        restart: "no"
        depends_on:
            - redis-container
        expose:
            - "4000-4010"
        ports:
            - "9229:9229"                                              
            - "4000:4000"                                                        

    redis-container:                                                  # Setting up ElastiCache local testing environment with redis
        image: redis
        command: ["redis-server", "--appendonly", "yes"]
        volumes:
           - ./.volumes/.redis-storage:/data        
        restart: always
        expose:
           - '6379'        
